images: "../data/raw_data/images"
masks: "../data/raw_data/masks"

train_masks: "../data/split_data/masks/train"
test_masks: "../data/split_data/masks/test"
train_images: "../data/split_data/images/train"
test_images: "../data/split_data/images/test"
valid_images: "../data/split_data/images/valid"
valid_masks: "../data/split_data/masks/valid"

model_path: '../best_model/saved_model.pth'
scores_path: '../scores/scores.txt'

batch_size: 16
epochs: 10000

